apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: numaresources-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NUMAResourcesOperator is the Schema for the numaresourcesoperators
        API
      displayName: NUMAResources Operator
      kind: NUMAResourcesOperator
      name: numaresourcesoperators.nodetopology.openshift.io
      version: v1alpha1
  description: NUMA resources exporter operator
  displayName: numaresources-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - RTE
  - NUMA
  links:
  - name: numaresources-operator
    url: https://github.com/openshift-kni/numaresources-operator
  maintainers:
  - email: fromani@redhat.com
    name: fromani
  maturity: alpha
  provider:
    name: Red Hat
  version: 4.10.0
